name: task_app
description: App Akademie Task App
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cached_network_image: ^3.2.3
  collection: ^1.17.2
  crypto: ^3.0.3
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  freezed_annotation: ^2.4.1
  google_fonts: ^5.1.0
  http: ^1.1.0
  image_picker: ^1.0.4
  json_annotation: ^4.8.0
  rive: ^0.12.3
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  photo_manager: ^3.0.0-dev.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  freezed: ^2.4.2
  build_runner: ^2.4.6
  flutter_lints: ^2.0.1

flutter:
  fonts:
    - family: Long
      fonts:
        - asset: assets/fonts/LongCang-Regular.ttf
    - family: Rubik
      fonts:
        - asset: assets/fonts/RubikGlitch-Regular.ttf
    - family: Maps
      fonts:
        - asset: assets/fonts/RubikMaps-Regular.ttf
    - family: Scribble
      fonts:
        - asset: assets/fonts/RubikScribble-Regular.ttf
    - family: Bungee
      fonts:
        - asset: assets/fonts/BungeeSpice-Regular.ttf
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/tasks/
    - assets/animations/
